CREATE TABLE PERSONA (
    DNI VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(30)
);

CREATE TABLE INSTRUCTOR (
    DNI VARCHAR(20) PRIMARY KEY,
    SUELDO DECIMAL(10,2),
    ANOS_EXPERIENCIA INT,
    FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE ALUMNOS (
    DNI VARCHAR(20) PRIMARY KEY,
    DIRECCION VARCHAR(50),
    FECHA_INSCRIPCION DATE,
    FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE TEST_TEORICOS (
    ID INT PRIMARY KEY,
    TIPO VARCHAR(20),
    TEST_APROBADOS INT,
    ERRORES_TOTALES INT,
    ACIERTOS INT,
    PREGUNTAS TEXT,
    OPCIONES TEXT,
    RESPUESTA_CORRECTA TEXT
);

CREATE TABLE AGENDA_INSTRUCTOR (
    ID INT PRIMARY KEY,
    HORARIO_CLASES VARCHAR(50),
    NIVEL_ALUMNOS VARCHAR(100),
    PREPARADOS_EXAMEN INT,
    DNI_INSTRUCTOR VARCHAR(20),
    FOREIGN KEY (DNI_INSTRUCTOR) REFERENCES INSTRUCTOR(DNI)
);

CREATE TABLE CLASE_PRACTICA (
    ID INT PRIMARY KEY,
    HUECOS_DISPONIBLES INT,
    PROFESORES_DISPONIBLES INT,
    CLASES_REALIZADAS INT,
    ID_AGENDA INT,
    FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA_INSTRUCTOR(ID)
);